[package]
name = "lktool"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
toml = { version = "0.8", features = ["preserve_order"] }
anyhow = "1.0"
colored = "2.1.0"
clap = { version = "4.5.4", features = ["derive"] }

[[bin]]
name = "lktool"
path = "src/main.rs"

[workspace]
