[package]
name = "axfs_ramfs"
version = "0.1.0"
edition = "2021"
authors = ["Yuekai Jia <equation618@gmail.com>"]
description = "RAM filesystem used by ArceOS"
license = "GPL-3.0-or-later OR Apache-2.0"
homepage = "https://github.com/rcore-os/arceos"
repository = "https://github.com/rcore-os/arceos/tree/main/crates/axfs_ramfs"
documentation = "https://rcore-os.github.io/arceos/axfs_ramfs/index.html"

[dependencies]
spin = "0.9"
log = "0.4"
axfs_vfs = { git = "ssh://git@github.com/shilei-massclouds/axfs_vfs.git" }
pipefs = { git = "ssh://git@github.com/shilei-massclouds/pipefs.git" }
axtype = { git = "ssh://git@github.com/shilei-massclouds/axtype.git" }
axfs_devfs = { git = "ssh://git@github.com/shilei-massclouds/axfs_devfs.git" }
