name: Run Tests

on:
  push:
    branches: [ main, os-checker ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Test
        run: |
          ./test_all.sh | tee stdout.txt

          echo '```text' >> $GITHUB_STEP_SUMMARY
          cat stdout.txt | awk "/Summary for tests/,/END/" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
